pipelines:
  default:
    - parallel:
      - step:
          image: node:14-alpine
          name: Build and Test
          script:
            - export NODE_OPTIONS=--max_old_space_size=1024
            - npm install --quiet                    
            - npx prisma db push --accept-data-loss
            - npm run-script build
            - npm run test:force 
          services:
            - postgres
            - docker
      - step: 
          image: maven:3.3.9
          name: SonarQube analysis
          script:
            - pipe: sonarsource/sonarqube-scan:1.0.0
              variables:
                SONAR_HOST_URL: ${SONAR_HOST_URL} # Get the value from the repository/workspace variable.
                SONAR_TOKEN: ${SONAR_TOKEN} # Get the value from the repository/workspace variable. You shouldn't set secret in clear text here.
definitions:
  services:
    docker:
      memory: 2048  #increasing docker service memory
    postgres:
      image: postgres:14-alpine
      memory: 1024
      environment:
        POSTGRES_DB: "admin"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "1234"
  caches:
    sonar: ~/.sonar